import modul_app.controller.api_key_controller
import modul_app.controller.auth_controller
import modul_app.controller.docx_controller
import modul_app.controller.main_controller
import modul_app.controller.process_controller
import modul_app.controller.user_controller
import modul_app.controller.xlsx_controller
